### ISSUE TITLE
[Suggestion] Adding Base Metals support and/or automatisation

### ISSUE THREAD

**Issue by Burgersim** [SinaMegapolis/MoreDyeableArmors#3]
Would it be possible to somehow make the Armor from Base Metals also dyable? The Metals are silver, copper, tin, lead, zinc, mercury, and nickel, as well as the fantasy metals cold-iron, mithril, adamantine, and star-steel. 
[**Mod Link**](https://minecraft.curseforge.com/projects/base-metals)

and/or

would it be possible to automate the process of adding dyable armor for every armor there is somehow via ore dictionary or sthg like that?

**Comment by SinaMegapolis** [comment]
oh yes i also want to make it automate the process for every armor
but it will take a while to do so since first i have to figure out how to do so
i can also make the armors themselves dyeable as wellbut it will take more time.

i'll try if i can do this for every armor but if i couldn't then i will focus on adding a version for each Bast Metals' armor

thanks for asking :ok_hand:

**Comment by Burgersim** [comment]
Thanks for the quick response ^^
